### ISSUE TITLE
NextStep 관련 문의드립니다

### ISSUE THREAD

**Issue by SeerslabCJ** [NaverCloudPlatform/ARCeyeARSDK#11]
ARSDK 의 NextStep 관련 문의드립니다

NextStep 오브젝트의 용도가
ARSDK 길찾기 사용 중 카메라가 TurnSpot 을 바라보고 있지 않을 때
TurnSpot 방향으로 카메라 회전을 유도하기 위한 용도로 사용되고 있는 것으로
ARSDK 문서를 통해 확인하였습니다

혹시 카메라가 방향과 상관없이 항상 TurnSpot 이 보이게 하는 옵션을 추가해주실 수 있는지 궁금합니다

확인 부탁드리며 답변 기다리겠습니다

**SDK 버전 : 1.2.5**

**Comment by yeongho-jeong** [comment]
별도의 옵션을 추가하지 않고 원하시는 효과를 구현하실 수 있습니다.
카메라의 방향과 상관 없이 NextStep을 항상 출력하고 싶으신 경우 다음 세 파일 `UnityNextStepArrow.cs`, `UnityNextStepDot.cs`, `UnityNextStepText.cs`의 `SetActive(bool)` 메서드에서 `SetOpacity(value ? 1 : 0);` 대신 `SetOpacity(1);`을 호출하시면 됩니다.

https://github.com/NaverCloudPlatform/ARCeyeARSDK/blob/9570a175e4d317a881e4ef10267d56f18bf79e38/Assets/ARPG/Core/Scripts/Item/UnityNextStepArrow.cs#L21-L24
https://github.com/NaverCloudPlatform/ARCeyeARSDK/blob/9570a175e4d317a881e4ef10267d56f18bf79e38/Assets/ARPG/Core/Scripts/Item/UnityNextStepDot.cs#L14-L18
https://github.com/NaverCloudPlatform/ARCeyeARSDK/blob/9570a175e4d317a881e4ef10267d56f18bf79e38/Assets/ARPG/Core/Scripts/Item/UnityNextStepText.cs#L20-L23

다음은 수정한 결과입니다.

https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/127068131/4e8d7b98-d061-4f55-98af-bfb578406de9

**Comment by SeerslabCJ** [comment]
빠른 답변 감사합니다

말씀해주신 코드를 ARSDK 샘플에 적용했을 때 잘 적용되는 것을 확인하였습니다
하지만 해당 코드를 저희 프로젝트에 적용하여 봤으나 다른 문제로 인해 해결되지 않았습니다

Scene 오브젝트의 하위로 있는 ARCeye.UnityNextStepArrow 가 특정 주기마다 destroy 되었다가 다시 instantiate 되는 문제가 있습니다
관련 스크립트로 추정되는 UnityNextStepArrow.cs 나 NextStep.cs 를 확인해보았으나 destroy 나 instantiate 코드를 찾지 못하였습니다

해당 부분 확인 한 번 부탁드립니다

관련 영상 첨부해서 공유드립니다

https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/164471597/7ff67d7c-cfb8-4101-92a4-20dbd36f6410

**Comment by yeongho-jeong** [comment]
NextStep의 생성과 삭제는 ARSDK의 내부 코드에서 관리하고 있습니다. NextStep은 길찾기에 성공했을때 생성이 되고 길찾기를 종료할때 삭제하고 있습니다. 첨부 주신 영상처럼 NextStep이 계속 생성되고 삭제가 되는 것은 길찾기를 계속 다시 시도하기 때문에 생성과 삭제가 반복되는 상황입니다.

ARSDK의 길찾기 로직에는 현재 경로에서 일정거리 이상 멀어지게 되면 길찾기를 다시 시도하는 로직이 들어있는데요, 첨부주신 영상과 같이 VL 응답의 오차가 큰 환경의 데이터로 테스트를 한다면 VL 응답을 수신했을때 길찾기 경로에서 멀어지게 되어 다시 길찾기를 수행하는 빈도가 잦아지게 됩니다. 이는 Editor에서 주로 발생하는 상황입니다만 실제 기기에서는 발생하지 않습니다.

혹시 원하시는 기능이 제가 첨부 드린 영상처럼 NextStep이 항상 출력되는 기능이 맞을까요? 내부 테스트 결과 길찾기 재시도를 하는 순간에 약간의 깜빡임이 있는 것을 제외하고는 항상 NextStep이 출력되는 것을 확인했습니다.

**Comment by SeerslabCJ** [comment]
네 현재 필요한 기능은 첨부해주신 영상처럼 NextStep이 항상 출력되는 기능이 맞습니다
에디터에서만 테스트를 진행해봤는데 말씀해주신대로 실제 기기에서 발생하지 않는다면 문제 없을 것 같습니다
실제 기기로 지하철 현장에서 확인해보겠습니다
확인 감사합니다
