### ISSUE TITLE
Amapper 실행 불가 에러 문의 드립니다

### ISSUE THREAD

**Issue by Yoon0yoon** [NaverCloudPlatform/ARCeyeARSDK#17]
현재 잘쓰고 있던 컴퓨터들이 일제히 Amapper가 실행이 안되는 상황이 발생했습니다.

프로그램을 실행시키면 켜지는듯 하다가 5초쯤 경과후 종료되어버립니다.

확인 부탁드립니다 (윈도우 , 맥 동일합니다)

**Comment by yeongho-jeong** [comment]
안녕하세요, 혹시 어떤 버전의 Amapper를 사용하시나요?

**Comment by Yoon0yoon** [comment]
1.6.1 입니다

**Comment by yeongho-jeong** [comment]
문제가 수정 된 1.6.3 버전이 배포 되었습니다. 해당 버전으로 업데이트 부탁드립니다
