### ISSUE TITLE
iOS 실행 오류 

### ISSUE THREAD

**Issue by GwonHyeok** [NaverCloudPlatform/ARCeyeARSDK#18]
ARCeyeARSDK 1.5.1 버전을 clone후 Build Setting 에서 iOS로 Switch Platform 진행해서 실행하면 스크립트를 로드할 수 없다고 나옵니다.
어떤 문제인지 알 수 있을까요??

<img width="1713" alt="스크린샷 2024-10-24 오후 11 01 50" src="https://github.com/user-attachments/assets/e9d141e5-5137-424b-8fa3-a1a99954f1cd">
<img width="1716" alt="스크린샷 2024-10-24 오후 11 03 37" src="https://github.com/user-attachments/assets/d192bfac-0341-40f7-b1c3-ebff6f0cdf30">

**Comment by yeongho-jeong** [comment]
안녕하세요, 해당 문제는 ARSDK 혹은 VLSDK의 define symbols이 정상적으로 설정되지 않아 발생한 문제입니다. 

v.1.5.1 업데이트에 각종 의존성 패키지들을 자동으로 설치하는 기능을 추가하기 위해 define symbols이 사용되기 시작했는데요, ARSDK 패키지를 빈 프로젝트에 직접 추가하면 필수 define symbols들을 자동으로 프로젝트에 추가하지만 예제 프로젝트에는 정상적으로 적용이 되지 않은 것 같습니다.

적용해야 하는 define symbols는 다음과 같습니다.
`VLSDK_ARFOUNDATION`
`VLSDK_NEWTONSOFT_JSON`
`ARSDK_GLTFAST`

해당 정보는 [VLSDK의 문서](https://ar.naverlabs.com/ARPG/docs/VLSDK_v1.6.5.html#:~:text=%EC%84%A4%EC%B9%98%EA%B0%80%20%EC%99%84%EB%A3%8C%EB%90%98%EB%A9%B4%20%EB%8B%A4%EC%9D%8C%20define%20symbols%EB%93%A4%EC%9D%B4%20%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C%20%EC%84%A4%EC%A0%95%EB%90%A9%EB%8B%88%EB%8B%A4.)와 [ARSDK의 문서](https://ar.naverlabs.com/ARPG/docs/ARSDK_v1.5.1.html#:~:text=%EC%84%A4%EC%B9%98%EA%B0%80%20%EC%99%84%EB%A3%8C%EB%90%98%EB%A9%B4%20%EB%8B%A4%EC%9D%8C%20define%20symbols%EB%93%A4%EC%9D%B4%20%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C%20%EC%84%A4%EC%A0%95%EB%90%A9%EB%8B%88%EB%8B%A4.)에서 확인하실 수 있습니다. 

지금 바로 예제 프로젝트를 실행해보시려면 위 define symbols를 iOS와 Android 플랫폼 각각에서 설정해주시면 됩니다.
Player Settings > iOS 혹은 Android 플랫폼 선택 -> Other Settings -> Script Compilation으로 이동 후 아래와 같이 설정한 뒤 Apply 버튼을 누르시면 됩니다.

![스크린샷 2024-10-25 오전 10 28 36](https://github.com/user-attachments/assets/bb744ade-cec9-4298-8bff-b378eda60e8a)
 
예제 프로젝트는 다음 업데이트 때 수정을 하도록 하겠습니다.

**Comment by GwonHyeok** [comment]
빠른 확인 감사합니다.
테스트 해보고 이슈 클로즈 하겠습니다!
