### ISSUE TITLE
winodws editor 기준 플레이모드 중지시 유니티 크래시

### ISSUE THREAD

**Issue by njelkom** [NaverCloudPlatform/ARCeyeARSDK#6]
유니티 에디터에서 Play -> 테스트진행 -> Play Stop 시 에디터 크래시가 발생합니다.

아래는 크래시 로그입니다.

=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ARCeye.ARPlayGround:DestroyPluginNative <0x000cd>
	  at ARCeye.ARPlayGround:OnDestroy <0x00082>
	  at System.Object:runtime_invoke_void__this__ <0x00187>
=================================================================

**Comment by yeongho-jeong** [comment]
Windows 환경에서 v1.2.5 버전을 적용시킨 ARSDK 샘플 프로젝트에 기본 제공되는 AMCO 지역을 로드하여 10회 가량 Play mode로 실행해보았으나 위 이슈가 재현되지 않았습니다.

샘플 프로젝트에서도 동일한 문제가 재발 되는지 확인이 필요할 것으로 보입니다.

추가로, Play mode에 진입했을때 `ARPG version 1.2.5, native 1.4.3` 로그가 출력되는지도 확인 부탁드립니다.

**Comment by njelkom** [comment]
네이티브는 1.3.3 으로 출력되고 있습니다.

![image](https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/7464793/bf8d8b35-962d-4bcd-9539-62ea2d336776)
