### ISSUE TITLE
미니맵 로드 시점

### ISSUE THREAD

**Issue by njelkom** [NaverCloudPlatform/ARCeyeARSDK#7]
현재 총 65개 역에 대해서 테스트를 진행 중에 있는데
일부 역에 대해 AMapper 에서 설정한 3d 맵이 노출되지 않는 문제점이 있습니다.

맵이 로드가되는 플로우가 궁금한데 ItemGenerator의 LoadModel 호출 시점을 알 수 있을까요

<img width="859" alt="image" src="https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/7464793/88fc3e05-f017-41ba-8b4c-364ae67f4219">

**Comment by yeongho-jeong** [comment]
맵 모델의 로드를 위한 `LoadModel` 메서드는 `ARPlayGround`의 `SetStage(string)` 메서드가 호출 직후에 호출됩니다. Stage 인식이 정상적으로 됐다면 AMapper에서 설정한 지도 모델 파일을 로드하게 됩니다. 
첨부주신 스크린샷을 볼 땐 AMapper의 설정에는 문제가 없는 것 같아 보이는데요, 어떤 플랫폼에서 해당 문제가 발생했나요? 그리고 스테이지 인식은 정상적으로 됐나요? 스테이지가 정상적으로 인식되지 않았을 때는 스테이지 인식 실패와 관련된 로그가 출력됩니다.

**Comment by njelkom** [comment]
아래 네이티브 버전 관련 이슈인듯 합니다.
다시한번 체크해보겠습니다.
