### ISSUE TITLE
ARPlayGround 이벤트 호출관련 이슈

### ISSUE THREAD

**Issue by njelkom** [NaverCloudPlatform/ARCeyeARSDK#8]
기존에 전달 드렸던 내용과 같은 내용인데

현장에 나가서 실 테스트 진행시
꼭 호출되어야하는 이벤트가 호출되고 있지 않습니다.

OnTransitMovingStarted
OnTransitMovingEnded
OnDestinationArrived

위 세가지 함수는 꼭 호출이 되어야 하는데 호출되지 않는 문제가 있습니다.

금일 제가 다시 현장에 나가서 테스트를 진행 할 예정인데 좀 더 자세한 로그 전달 드릴 수 있도록 하겠습니다.

<img width="383" alt="image" src="https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/7464793/de110ce1-ec96-467f-9f29-100078a3250f">

**Comment by yeongho-jeong** [comment]
해당 문제는 #2 하고 같은 문제로 보입니다. NextStep.prefab을 추가해도 호출이 되지 않는지 확인 부탁드립니다.

**Comment by njelkom** [comment]
NextStep -> Prefab/NextStep 추가 되어 있습니다.

부평역 내부에서 목표 플랫폼까지의 이동 로그입니다. 이동수단 에스컬레이터 설정 후 이동 했습니다.

![image](https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/7464793/3a66cd09-f2cf-4f6a-8bce-2ccb392c2c78)

[com.seerslab.incheonar-logcat_2.txt](https://github.com/NaverCloudPlatform/ARCeyeARSDK/files/13596910/com.seerslab.incheonar-logcat_2.txt)

**Comment by yeongho-jeong** [comment]
로그를 확인해본 결과 NextStep과 관련된 요소들이 정상적으로 생성되지 않을 것 같습니다.

몇가지 확인이 필요할 것 같습니다.

1. AMapper의 Indicator Config에서 모델 파일 경로 이외에 따로 수정된 사항이 있을까요?

2. 길찾기를 요청하는 순간에 NextStep이 Scene에 추가 되어 있을까요? [링크](https://ar.naverlabs.com/ARPG/docs/ARSDK_v1.2.5.html#page-top:~:text=%EC%9E%85%EB%A0%A5%ED%96%88%EB%8A%94%EC%A7%80%20%ED%99%95%EC%9D%B8%EC%9D%B4%20%ED%95%84%EC%9A%94%ED%95%A9%EB%8B%88%EB%8B%A4.-,4.%20ARSDK%EB%A5%BC%20%EA%B5%AC%EC%84%B1%ED%95%98%EB%8A%94%20%ED%95%84%EC%88%98%20%EC%9A%94%EC%86%8C,-ARSDK%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EB%8A%94%20%EC%95%84%EB%9E%98%EC%97%90)의 사진과 같이 Scene에 추가 되어 있는 상태이어야 합니다.

다음과 같이 NextStep과 관련된 요소들이 출력되어야 Transit 관련 콜백을 받을 수 있습니다.

![스크린샷 2023-12-07 오후 5 41 04](https://github.com/NaverCloudPlatform/ARCeyeARSDK/assets/127068131/1f7fdab4-2fe9-426e-84f4-3b0042311a0f)

**Comment by njelkom** [comment]
네 확인 했습니다! 제가 사용법 관련 해서 잘못 사용 하고 있었습니다.
피드백 주신대로 설정 하고 다시한번 테스트 해보겠습니다.
